Only test under MacOs now.

* prepare
** install isync
   You should have ~brew~ installed. If not, you can download from [[https://brew.sh/][here]]

   ~brew install isync~

** install mu
   ~brew install mu~

** install gpg
   Use ~gpg~ to encrypt email password.

   ~brew install gnupg gnupg2~

** create gpg password
   - create a file and write your email password in it. For example: ~echo my-password > ​~/pass~
   - use gpg encrypt the file with password: ~gpg -c -o ​~​~/pass.gpg ​~/pass~
   - then config ​~​~/pass.gpg~ to ~.mbsyncrc~ 's ~PassCmd~, see below

** config isync
   - create a folder, ~mkdir ~/Maildir~
   - create a file, ​~​~/.mbsyncrc~

   fullill ~.mbsyncrc~ with your email config, for example:

   #+begin_src bash
     # Remote IMAP account
     # your email IMAP config
     IMAPAccount spike
     Host outlook.office365.com
     Port 993
     User <your-email-address>
     # your need to use gpg to decript your pass if you have encrypted
     PassCmd "gpg -q --for-your-eyes-only --no-tty -d ~/pass.gpg"
     # if you do not encrypt your pass, you can use this:
     # Pass <your email password>
     SSLType IMAPS
     SSLVersions TLSv1.2

     # Remote Store
     # outlook-remote-spike is `Far`
     IMAPStore outlook-remote-spike
     Account l-yanlei

     # outlook-local-spike is `Near`
     MaildirStore outlook-local-spike
     # where to save your email
     Path ~/Maildir/spike
     # where to save your inbox
     Inbox ~/Maildir/spike/INBOX
     SubFolders Verbatim

     # Channels
     Channel outlook-spike
     Far :outlook-remote-spike:
     Near :outlook-local-spike:
     Patterns *
     Expunge None
     CopyArrivalDate yes
     Sync All
     Create Near
     SyncState *

     # Group
   #+end_src

   For more info, you can find [[https://wiki.archlinux.org/title/isync][here]].
** download your email
   ~mbsync -a~

   This may take a long time if you have lots of emails.
** use mu to index your email
   ~mu init~

   By default, mu will try to index your email under ~~/.Maildir~

* Get started
  #+begin_src bash
    git clone https://github.com/Spike-Leung/invoice-compress.git
    cd invoice-compress
    yarn
    yarn extract
  #+end_src


** Specify date range
   By default, this script will extract all invoice in this month.

   But you can also specify a time range to extract. For example:

   ~yarn extract 20220401...20220502~


* How it works
  - use ~isync~ to download all emails
  - use ~mu~ to index, find, and extract pdf in emails
  - use ~mu~ to find invoice email without pdf, but have a download links
  - use ~mailParser~ parse the email, and use ~jsdom~ query the download links
  - then use ~http~ and ~https~ node module to download pdf from links
  - if there are links can not download directly, write a adapter which use ~puppeteer~ or something else to find the download links
* todos
  - [ ] calculate invoice sum
